# Spark: San-Francisco fire calls project

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Описание-проекта" data-toc-modified-id="Описание-проекта-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Описание проекта</a></span></li><li><span><a href="#Подготовка" data-toc-modified-id="Подготовка-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Подготовка</a></span></li><li><span><a href="#Примеры-работ-в-Spark" data-toc-modified-id="Примеры-работ-в-Spark-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Примеры работ в Spark</a></span><ul class="toc-item"><li><span><a href="#Схема" data-toc-modified-id="Схема-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Схема</a></span></li><li><span><a href="#Чтение-файла" data-toc-modified-id="Чтение-файла-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Чтение файла</a></span></li><li><span><a href="#Кэширование-данных-и-вывод-схемы" data-toc-modified-id="Кэширование-данных-и-вывод-схемы-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Кэширование данных и вывод схемы</a></span></li><li><span><a href="#Вывод-первых-строк" data-toc-modified-id="Вывод-первых-строк-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Вывод первых строк</a></span></li><li><span><a href="#Вывод-строк-по-условию" data-toc-modified-id="Вывод-строк-по-условию-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Вывод строк по условию</a></span></li><li><span><a href="#Условие,-агрегация,-переименование" data-toc-modified-id="Условие,-агрегация,-переименование-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Условие, агрегация, переименование</a></span></li><li><span><a href="#Новый-датафрейм" data-toc-modified-id="Новый-датафрейм-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Новый датафрейм</a></span></li><li><span><a href="#Distinct" data-toc-modified-id="Distinct-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Distinct</a></span></li><li><span><a href="#Новый-датафрейм,-переименование,-условие" data-toc-modified-id="Новый-датафрейм,-переименование,-условие-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>Новый датафрейм, переименование, условие</a></span></li><li><span><a href="#Преобразование-типов-данных" data-toc-modified-id="Преобразование-типов-данных-3.10"><span class="toc-item-num">3.10&nbsp;&nbsp;</span>Преобразование типов данных</a></span></li><li><span><a href="#Серия-преобразований" data-toc-modified-id="Серия-преобразований-3.11"><span class="toc-item-num">3.11&nbsp;&nbsp;</span>Серия преобразований</a></span></li><li><span><a href="#Avg,-Min,-Max" data-toc-modified-id="Avg,-Min,-Max-3.12"><span class="toc-item-num">3.12&nbsp;&nbsp;</span>Avg, Min, Max</a></span></li></ul></li><li><span><a href="#Ответы-на-вопросы" data-toc-modified-id="Ответы-на-вопросы-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ответы на вопросы</a></span><ul class="toc-item"><li><span><a href="#Q-1)-How-many-distinct-types-of-calls-were-made-to-the-Fire-Department?" data-toc-modified-id="Q-1)-How-many-distinct-types-of-calls-were-made-to-the-Fire-Department?-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Q-1) How many distinct types of calls were made to the Fire Department?</a></span></li><li><span><a href="#Q-2)-What-are-distinct-types-of-calls-were-made-to-the-Fire-Department?" data-toc-modified-id="Q-2)-What-are-distinct-types-of-calls-were-made-to-the-Fire-Department?-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Q-2) What are distinct types of calls were made to the Fire Department?</a></span></li><li><span><a href="#Q-3)-Find-out-all-response-or-delayed-times-greater-than-5-mins?" data-toc-modified-id="Q-3)-Find-out-all-response-or-delayed-times-greater-than-5-mins?-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Q-3) Find out all response or delayed times greater than 5 mins?</a></span></li><li><span><a href="#Q-4a)-What-zip-codes-accounted-for-most-common-calls?" data-toc-modified-id="Q-4a)-What-zip-codes-accounted-for-most-common-calls?-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Q-4a) What zip codes accounted for most common calls?</a></span></li><li><span><a href="#Q-5)-What-was-the-sum-of-all-calls,-average,-min-and-max-of-the-response-times-for-calls?" data-toc-modified-id="Q-5)-What-was-the-sum-of-all-calls,-average,-min-and-max-of-the-response-times-for-calls?-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Q-5) What was the sum of all calls, average, min and max of the response times for calls?</a></span></li><li><span><a href="#Q-6b)-What-week-of-the-year-in-2018-had-the-most-fire-calls?" data-toc-modified-id="Q-6b)-What-week-of-the-year-in-2018-had-the-most-fire-calls?-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Q-6b) What week of the year in 2018 had the most fire calls?</a></span></li><li><span><a href="#Q-7)-What-neighborhoods-in-San-Francisco-had-the-worst-response-time-in-2018?" data-toc-modified-id="Q-7)-What-neighborhoods-in-San-Francisco-had-the-worst-response-time-in-2018?-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Q-7) What neighborhoods in San Francisco had the worst response time in 2018?</a></span></li></ul></li></ul></div>

## Описание проекта

В данной тетради - практика работы со Spark. 


Условно можно разделить содержимое на 3 категории:


1. Подготовка к использованию Spark в Jupyter Notebook


2. Практика использования Spark: открытие файла, трансформация датафрейма, расчёт показателей и вывод на экран результатов. Этот раздел был пройден на курсе.


3. Самостоятельная часть: ответы на вопросы при помощи Spark.


## Подготовка

Устанавливаем необходимые библиотеки:

In [1]:
import findspark
findspark.init()
import pyspark

from pyspark.sql import SparkSession

from pyspark.sql.types import *
import pyspark.sql.functions as F

Задаём Спарк-сессию:

In [2]:
spark = (SparkSession
        .builder
        .appName("PythonFireProject")
        .getOrCreate())

## Примеры работ в Spark

### Схема

In [3]:
# Programmatic way to define a schema 
fire_schema = StructType([StructField('CallNumber', IntegerType(), True),
                     StructField('UnitID', StringType(), True),
                     StructField('IncidentNumber', IntegerType(), True),
                     StructField('CallType', StringType(), True),                  
                     StructField('CallDate', StringType(), True),      
                     StructField('WatchDate', StringType(), True),
                     StructField('CallFinalDisposition', StringType(), True),
                     StructField('AvailableDtTm', StringType(), True),
                     StructField('Address', StringType(), True),       
                     StructField('City', StringType(), True),       
                     StructField('Zipcode', IntegerType(), True),       
                     StructField('Battalion', StringType(), True),                 
                     StructField('StationArea', StringType(), True),       
                     StructField('Box', StringType(), True),       
                     StructField('OriginalPriority', StringType(), True),       
                     StructField('Priority', StringType(), True),       
                     StructField('FinalPriority', IntegerType(), True),       
                     StructField('ALSUnit', BooleanType(), True),       
                     StructField('CallTypeGroup', StringType(), True),
                     StructField('NumAlarms', IntegerType(), True),
                     StructField('UnitType', StringType(), True),
                     StructField('UnitSequenceInCallDispatch', IntegerType(), True),
                     StructField('FirePreventionDistrict', StringType(), True),
                     StructField('SupervisorDistrict', StringType(), True),
                     StructField('Neighborhood', StringType(), True),
                     StructField('Location', StringType(), True),
                     StructField('RowID', StringType(), True),
                     StructField('Delay', FloatType(), True)])

### Чтение файла

In [4]:
# Use the DataFrameReader interface to read a CSV file
sf_fire_file = "C:\datasets\sf-fire-calls.csv"
fire_df = spark.read.csv(sf_fire_file, header=True, schema=fire_schema)

### Кэширование данных и вывод схемы

In [5]:
# Cache the DataFrame since we will be performing some operations on it.
fire_df.cache()
fire_df.count()

fire_df.printSchema()

root
 |-- CallNumber: integer (nullable = true)
 |-- UnitID: string (nullable = true)
 |-- IncidentNumber: integer (nullable = true)
 |-- CallType: string (nullable = true)
 |-- CallDate: string (nullable = true)
 |-- WatchDate: string (nullable = true)
 |-- CallFinalDisposition: string (nullable = true)
 |-- AvailableDtTm: string (nullable = true)
 |-- Address: string (nullable = true)
 |-- City: string (nullable = true)
 |-- Zipcode: integer (nullable = true)
 |-- Battalion: string (nullable = true)
 |-- StationArea: string (nullable = true)
 |-- Box: string (nullable = true)
 |-- OriginalPriority: string (nullable = true)
 |-- Priority: string (nullable = true)
 |-- FinalPriority: integer (nullable = true)
 |-- ALSUnit: boolean (nullable = true)
 |-- CallTypeGroup: string (nullable = true)
 |-- NumAlarms: integer (nullable = true)
 |-- UnitType: string (nullable = true)
 |-- UnitSequenceInCallDispatch: integer (nullable = true)
 |-- FirePreventionDistrict: string (nullable = true)
 

### Вывод первых строк

In [6]:
#display(fire_df.limit(5))
fire_df.show(5, False)

+----------+------+--------------+----------------+----------+----------+--------------------+----------------------+---------------------------+----+-------+---------+-----------+----+----------------+--------+-------------+-------+-------------+---------+--------+--------------------------+----------------------+------------------+---------------------+-------------------------------------+-------------+---------+
|CallNumber|UnitID|IncidentNumber|CallType        |CallDate  |WatchDate |CallFinalDisposition|AvailableDtTm         |Address                    |City|Zipcode|Battalion|StationArea|Box |OriginalPriority|Priority|FinalPriority|ALSUnit|CallTypeGroup|NumAlarms|UnitType|UnitSequenceInCallDispatch|FirePreventionDistrict|SupervisorDistrict|Neighborhood         |Location                             |RowID        |Delay    |
+----------+------+--------------+----------------+----------+----------+--------------------+----------------------+---------------------------+----+-------+--

### Вывод строк по условию

In [7]:
# Filter out "Medical Incident" call types

# Note that filter() and where() methods on the DataFrame are similar. 
# Check relevant documentation for their respective argument types.

few_fire_df = (fire_df
               .select("IncidentNumber", "AvailableDtTm", "CallType")
               .where(F.col("CallType") != "Medical Incident"))

few_fire_df.show(5, truncate=False)

+--------------+----------------------+--------------+
|IncidentNumber|AvailableDtTm         |CallType      |
+--------------+----------------------+--------------+
|2003235       |01/11/2002 01:51:44 AM|Structure Fire|
|2003250       |01/11/2002 04:16:46 AM|Vehicle Fire  |
|2003259       |01/11/2002 06:01:58 AM|Alarms        |
|2003279       |01/11/2002 08:03:26 AM|Structure Fire|
|2003301       |01/11/2002 09:46:44 AM|Alarms        |
+--------------+----------------------+--------------+
only showing top 5 rows



### Условие, агрегация, переименование

Посмотрим, сколько различных видов звонков (с непустыми значениями звонков)

In [8]:
# return number of distinct types of calls using countDistinct()

(fire_df
  .select("CallType")
  .where(F.col("CallType").isNotNull())
  .agg(F.countDistinct("CallType").alias("DistinctCallTypes"))
  .show())

(fire_df
  .select("CallType")
  .where(F.col("CallType").isNotNull())
  .distinct()
  .count())

+-----------------+
|DistinctCallTypes|
+-----------------+
|               30|
+-----------------+



30

### Новый датафрейм

Смотрим на детали некоторых звонков, которые не связаны с медицинскими происшествиями:

In [9]:
# Example
few_fire_df = (fire_df
  .select("IncidentNumber", "AvailableDtTm", "CallType") 
  .where(F.col("CallType") != "Medical Incident"))
few_fire_df.show(5, truncate=False)

+--------------+----------------------+--------------+
|IncidentNumber|AvailableDtTm         |CallType      |
+--------------+----------------------+--------------+
|2003235       |01/11/2002 01:51:44 AM|Structure Fire|
|2003250       |01/11/2002 04:16:46 AM|Vehicle Fire  |
|2003259       |01/11/2002 06:01:58 AM|Alarms        |
|2003279       |01/11/2002 08:03:26 AM|Structure Fire|
|2003301       |01/11/2002 09:46:44 AM|Alarms        |
+--------------+----------------------+--------------+
only showing top 5 rows



### Distinct

Смотрим 10 различных видов звонков:

In [10]:
# filter for only distinct non-null CallTypes from all the rows
(fire_df
  .select("CallType")
  .where(F.col("CallType").isNotNull())
  .distinct()
  .show(10, False))

+-----------------------------+
|CallType                     |
+-----------------------------+
|Elevator / Escalator Rescue  |
|Aircraft Emergency           |
|Alarms                       |
|Odor (Strange / Unknown)     |
|Citizen Assist / Service Call|
|HazMat                       |
|Explosion                    |
|Oil Spill                    |
|Vehicle Fire                 |
|Suspicious Package           |
+-----------------------------+
only showing top 10 rows



### Новый датафрейм, переименование, условие 

Смотрим на 5 значений в ситуациях, когда ответ был задержан более чем на 5 минут:

In [11]:
# Rename column
new_fire_df = fire_df.withColumnRenamed("Delay", "ResponseDelayedinMins")
(new_fire_df
  .select("ResponseDelayedinMins")
  .where(F.col("ResponseDelayedinMins") > 5)
  .show(5, False))

+---------------------+
|ResponseDelayedinMins|
+---------------------+
|5.35                 |
|6.25                 |
|5.2                  |
|5.6                  |
|7.25                 |
+---------------------+
only showing top 5 rows



### Преобразование типов данных

Преобразуем файл: приводим тип данных времени и переименовываем колонки, удаляя ненужные

In [12]:
# date operations
fire_ts_df = (new_fire_df
  .withColumn("IncidentDate", F.to_timestamp(F.col("CallDate"), "MM/dd/yyyy"))
  .drop("CallDate") 
  .withColumn("OnWatchDate", F.to_timestamp(F.col("WatchDate"), "MM/dd/yyyy"))
  .drop("WatchDate") 
  .withColumn("AvailableDtTS", F.to_timestamp(F.col("AvailableDtTm"), 
  "MM/dd/yyyy hh:mm:ss a"))
  .drop("AvailableDtTm"))

Смотрим на первые строки новых колонок с приведенным типом данных:

In [13]:
# Select the converted columns
(fire_ts_df
  .select("IncidentDate", "OnWatchDate", "AvailableDtTS")
  .show(5, False))

+-------------------+-------------------+-------------------+
|IncidentDate       |OnWatchDate        |AvailableDtTS      |
+-------------------+-------------------+-------------------+
|2002-01-11 00:00:00|2002-01-10 00:00:00|2002-01-11 01:51:44|
|2002-01-11 00:00:00|2002-01-10 00:00:00|2002-01-11 03:01:18|
|2002-01-11 00:00:00|2002-01-10 00:00:00|2002-01-11 02:39:50|
|2002-01-11 00:00:00|2002-01-10 00:00:00|2002-01-11 04:16:46|
|2002-01-11 00:00:00|2002-01-10 00:00:00|2002-01-11 06:01:58|
+-------------------+-------------------+-------------------+
only showing top 5 rows



### Серия преобразований

Смотрим топ-10 частных причин вызовов:

In [14]:
# what were the most common types of fire calls?
(fire_ts_df
  .select("CallType")
  .where(F.col("CallType").isNotNull())
  .groupBy("CallType")
  .count()
  .orderBy("count", ascending=False)
  .show(n=10, truncate=False))

+-------------------------------+------+
|CallType                       |count |
+-------------------------------+------+
|Medical Incident               |113794|
|Structure Fire                 |23319 |
|Alarms                         |19406 |
|Traffic Collision              |7013  |
|Citizen Assist / Service Call  |2524  |
|Other                          |2166  |
|Outside Fire                   |2094  |
|Vehicle Fire                   |854   |
|Gas Leak (Natural and LP Gases)|764   |
|Water Rescue                   |755   |
+-------------------------------+------+
only showing top 10 rows



### Avg, Min, Max

Смотрим: сколько всего звонков, среднее время ответа в минутах, минимальное и максимальное время ответа

In [15]:
# min,max, avg
(fire_ts_df
  .select(F.sum("NumAlarms"), F.avg("ResponseDelayedinMins"),
    F.min("ResponseDelayedinMins"), F.max("ResponseDelayedinMins"))
  .show())

+--------------+--------------------------+--------------------------+--------------------------+
|sum(NumAlarms)|avg(ResponseDelayedinMins)|min(ResponseDelayedinMins)|max(ResponseDelayedinMins)|
+--------------+--------------------------+--------------------------+--------------------------+
|        176170|         3.892364154521585|               0.016666668|                   1844.55|
+--------------+--------------------------+--------------------------+--------------------------+



## Ответы на вопросы

### Q-1) How many distinct types of calls were made to the Fire Department?


To be sure, let's not count "null" strings in that column.

In [16]:
(fire_df
  .select("CallType")
  .where(F.col("CallType").isNotNull())
  .distinct()
  .count())


30

### Q-2) What are distinct types of calls were made to the Fire Department?


These are all the distinct type of call to the SF Fire Department

In [17]:
(fire_df
    .select("CallType")
    .where(F.col("CallType").isNotNull())
    .distinct()
    .orderBy("CallType")
    .show(n=50, truncate=False))

+--------------------------------------------+
|CallType                                    |
+--------------------------------------------+
|Administrative                              |
|Aircraft Emergency                          |
|Alarms                                      |
|Assist Police                               |
|Citizen Assist / Service Call               |
|Confined Space / Structure Collapse         |
|Electrical Hazard                           |
|Elevator / Escalator Rescue                 |
|Explosion                                   |
|Extrication / Entrapped (Machinery, Vehicle)|
|Fuel Spill                                  |
|Gas Leak (Natural and LP Gases)             |
|HazMat                                      |
|High Angle Rescue                           |
|Industrial Accidents                        |
|Marine Fire                                 |
|Medical Incident                            |
|Mutual Aid / Assist Outside Agency          |
|Odor (Strang

### Q-3) Find out all response or delayed times greater than 5 mins?


Rename the column Delay - > ReponseDelayedinMins


Returns a new DataFrame


Find out all calls where the response time to the fire site was delayed for more than 5 mins

In [18]:
new_fire_df = fire_df.withColumnRenamed("Delay", "ResponseDelayedinMins")
(new_fire_df
  .select("CallType", "ResponseDelayedinMins")
  .where(F.col("ResponseDelayedinMins") > 5)
  .orderBy("ResponseDelayedinMins", ascending=False)
  .show(50, False))

+----------------------------------+---------------------+
|CallType                          |ResponseDelayedinMins|
+----------------------------------+---------------------+
|Alarms                            |1844.55              |
|Structure Fire                    |1370.2333            |
|Structure Fire                    |949.11664            |
|Structure Fire                    |931.45               |
|Structure Fire                    |751.93335            |
|Structure Fire                    |734.05               |
|Medical Incident                  |721.4                |
|Assist Police                     |628.61664            |
|Structure Fire                    |535.93335            |
|Structure Fire                    |491.26666            |
|Structure Fire                    |437.8                |
|Structure Fire                    |424.58334            |
|Structure Fire                    |414.85               |
|Train / Rail Incident             |406.63333           

### Q-4a) What zip codes accounted for most common calls?


Let's investigate what zip codes in San Francisco accounted for most fire calls and what type where they.


Filter out by CallType


Group them by CallType and Zip code


Count them and display them in descending order


It seems like the most common calls were all related to Medical Incident, and the two zip codes are 94102 and 94103.

In [19]:
(fire_df
    .select("CallType", "Zipcode")
    .where(F.col("CallType").isNotNull())
    .groupBy("CallType", "Zipcode")
    .count()
    .orderBy("count", ascending=False)
    .show(n=50, truncate=False))

+-----------------+-------+-----+
|CallType         |Zipcode|count|
+-----------------+-------+-----+
|Medical Incident |94102  |16130|
|Medical Incident |94103  |14775|
|Medical Incident |94110  |9995 |
|Medical Incident |94109  |9479 |
|Medical Incident |94124  |5885 |
|Medical Incident |94112  |5630 |
|Medical Incident |94115  |4785 |
|Medical Incident |94122  |4323 |
|Medical Incident |94107  |4284 |
|Medical Incident |94133  |3977 |
|Medical Incident |94117  |3522 |
|Medical Incident |94134  |3437 |
|Medical Incident |94114  |3225 |
|Medical Incident |94118  |3104 |
|Medical Incident |94121  |2953 |
|Medical Incident |94116  |2738 |
|Medical Incident |94132  |2594 |
|Structure Fire   |94110  |2267 |
|Medical Incident |94105  |2258 |
|Structure Fire   |94102  |2229 |
|Structure Fire   |94103  |2221 |
|Alarms           |94103  |2168 |
|Medical Incident |94108  |2162 |
|Structure Fire   |94109  |2160 |
|Alarms           |94102  |2140 |
|Medical Incident |94123  |1940 |
|Medical Incid

Q-4b) What San Francisco neighborhoods are in the zip codes 94102 and 94103


Let's find out the neighborhoods associated with these two zip codes. In all likelihood, these are some of the contested neighborhood with high reported crimes.

In [20]:
(fire_df
    .select("CallType", "Zipcode", "Neighborhood")
    .where(F.col("CallType").isNotNull())
     .where(F.col("Zipcode") == 94102)
    .groupBy("Zipcode", "Neighborhood")
    .count()
    .orderBy("count", ascending=False)
    .show(truncate=False))

(fire_df
    .select("CallType", "Zipcode", "Neighborhood")
    .where(F.col("CallType").isNotNull())
     .where(F.col("Zipcode") == 94103)
    .groupBy("Zipcode", "Neighborhood")
    .count()
    .orderBy("count", ascending=False)
    .show(truncate=False))

+-------+------------------------------+-----+
|Zipcode|Neighborhood                  |count|
+-------+------------------------------+-----+
|94102  |Tenderloin                    |17084|
|94102  |Hayes Valley                  |2814 |
|94102  |Western Addition              |910  |
|94102  |Financial District/South Beach|446  |
|94102  |Nob Hill                      |332  |
|94102  |South of Market               |254  |
+-------+------------------------------+-----+

+-------+------------------------------+-----+
|Zipcode|Neighborhood                  |count|
+-------+------------------------------+-----+
|94103  |South of Market               |13762|
|94103  |Mission                       |5445 |
|94103  |Financial District/South Beach|1090 |
|94103  |Tenderloin                    |324  |
|94103  |Mission Bay                   |167  |
|94103  |Hayes Valley                  |53   |
|94103  |Castro/Upper Market           |51   |
|94103  |Potrero Hill                  |5    |
+-------+---

### Q-5) What was the sum of all calls, average, min and max of the response times for calls?


Let's use the built-in Spark SQL functions to compute the sum, avg, min, and max of few columns:


Number of Total Alarms


What were the min and max the delay in response time before the Fire Dept arrived at the scene of the call

In [21]:
(fire_ts_df
  .select(F.sum("NumAlarms"), F.avg("ResponseDelayedinMins"),
    F.min("ResponseDelayedinMins"), F.max("ResponseDelayedinMins"))
  .show())

+--------------+--------------------------+--------------------------+--------------------------+
|sum(NumAlarms)|avg(ResponseDelayedinMins)|min(ResponseDelayedinMins)|max(ResponseDelayedinMins)|
+--------------+--------------------------+--------------------------+--------------------------+
|        176170|         3.892364154521585|               0.016666668|                   1844.55|
+--------------+--------------------------+--------------------------+--------------------------+



### Q-6b) What week of the year in 2018 had the most fire calls?


Note: Week 1 is the New Years' week and week 25 is the July 4 the week. Loads of fireworks, so it makes sense the higher number of calls.

In [22]:
fire_ts_df_2018 = (fire_ts_df
     .where(F.expr("EXTRACT(YEAR FROM IncidentDate)")==2018))

(fire_ts_df_2018
     .select("IncidentDate")
     .where(F.col("CallType").isNotNull())
     .withColumn(
    "IncidentWeek_2018",
        F.expr("EXTRACT(WEEK FROM IncidentDate)"),
)
    .groupBy("IncidentWeek_2018")
    .count()
    .orderBy("count", ascending=False)
    .show(truncate=False))

+-----------------+-----+
|IncidentWeek_2018|count|
+-----------------+-----+
|22               |259  |
|40               |255  |
|43               |250  |
|25               |249  |
|1                |246  |
|44               |244  |
|13               |243  |
|32               |243  |
|11               |240  |
|5                |236  |
|18               |236  |
|23               |235  |
|31               |234  |
|42               |234  |
|2                |234  |
|19               |233  |
|8                |232  |
|34               |232  |
|10               |232  |
|28               |231  |
+-----------------+-----+
only showing top 20 rows



###  Q-7) What neighborhoods in San Francisco had the worst response time in 2018?


It appears that if you living in Presidio Heights, the Fire Dept arrived in less than 3 mins, while Mission Bay took more than 6 mins.

In [23]:
fire_ts_df_2018 = (fire_ts_df
     .where(F.expr("EXTRACT(YEAR FROM IncidentDate)")==2018))

(fire_ts_df_2018
     .select("Neighborhood", "ResponseDelayedinMins")
     .where(F.col("CallType").isNotNull())
    .groupBy("Neighborhood")
    .avg("ResponseDelayedinMins")
    .orderBy('avg(ResponseDelayedinMins)', ascending=False)
    .show(50,truncate=False))

+------------------------------+--------------------------+
|Neighborhood                  |avg(ResponseDelayedinMins)|
+------------------------------+--------------------------+
|Chinatown                     |6.190314101143033         |
|Presidio                      |5.829227011272873         |
|Treasure Island               |5.453703684111436         |
|McLaren Park                  |4.74404764175415          |
|Bayview Hunters Point         |4.620561962212182         |
|Presidio Heights              |4.594131482319093         |
|Inner Sunset                  |4.438095217981896         |
|Inner Richmond                |4.364728709292966         |
|Financial District/South Beach|4.344084616885593         |
|Haight Ashbury                |4.266428579390049         |
|Seacliff                      |4.26111114025116          |
|West of Twin Peaks            |4.190952391851516         |
|Potrero Hill                  |4.190555579037893         |
|Pacific Heights               |4.180453